package store

var createTableStatements = []string{
	`CREATE TABLE IF NOT EXISTS diagnose_records (id varchar(64) PRIMARY KEY,target_ip varchar(64),` + "`trigger`" + ` varchar(32),source varchar(64),data_source varchar(64),status varchar(32),report longtext,summary_report longtext,raw_report longtext,alert_title varchar(255),create_time datetime,end_time datetime NULL,INDEX idx_diag_ip_time(target_ip,create_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS catpaw_agents (ip varchar(64) PRIMARY KEY,hostname varchar(255),version varchar(64),last_seen datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS credentials (id varchar(64) PRIMARY KEY,name varchar(255),protocol varchar(32),username varchar(255),password text,ssh_key longtext,port int,remark text) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS alerts (id varchar(64) PRIMARY KEY,title varchar(255),target_ip varchar(64),severity varchar(32),status varchar(32),labels json,source varchar(64),create_time datetime,resolved_at datetime NULL,INDEX idx_alert_time(create_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS chat_sessions (id varchar(64) PRIMARY KEY,title varchar(255),model varchar(128),target_ip varchar(64),created_at datetime,updated_at datetime,INDEX idx_chat_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS chat_messages (id varchar(64) PRIMARY KEY,session_id varchar(64),role varchar(32),content longtext,model varchar(128),target_ip varchar(64),created_at datetime,INDEX idx_msg_session(session_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS topology_nodes (id varchar(64) PRIMARY KEY,name varchar(255),type varchar(64),ip varchar(64),service_name varchar(255),port int,status varchar(32),x double,y double,meta text,created_at datetime,updated_at datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS topology_edges (id varchar(64) PRIMARY KEY,source_id varchar(64),target_id varchar(64),protocol varchar(64),direction varchar(32),label varchar(255),status varchar(32),latency_ms int,error text,created_at datetime,updated_at datetime,UNIQUE KEY uniq_edge(source_id,target_id,protocol)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS topology_businesses (id varchar(64) PRIMARY KEY,name varchar(255),hosts json,endpoints json,attributes json,graph longtext,created_at datetime,updated_at datetime,INDEX idx_topology_business_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS audit_events (id varchar(64) PRIMARY KEY,action varchar(128),target varchar(255),risk varchar(32),decision varchar(64),detail text,operator varchar(128),description text,test_batch_id varchar(128),client_ip varchar(64),created_at datetime,INDEX idx_audit_batch(test_batch_id),INDEX idx_audit_time(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS user_profiles (id varchar(64) PRIMARY KEY,name varchar(255) NOT NULL,hosts json,endpoints json,description text,created_at datetime,updated_at datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS users (id varchar(64) PRIMARY KEY,username varchar(128) UNIQUE NOT NULL,password_hash varchar(255) NOT NULL,role varchar(32) DEFAULT 'user',must_change_pwd tinyint(1) DEFAULT 0,created_at datetime,updated_at datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_user_profiles (user_id varchar(64) PRIMARY KEY,nickname varchar(128),email varchar(255),phone varchar(64),contacts_json json,last_active_at bigint DEFAULT 0,created_at datetime,updated_at datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_teams (id varchar(64) PRIMARY KEY,name varchar(255) NOT NULL,note text,parent_id varchar(64),created_at datetime,updated_at datetime,INDEX idx_org_team_parent(parent_id),INDEX idx_org_team_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_team_members (team_id varchar(64) NOT NULL,user_id varchar(64) NOT NULL,created_at datetime,PRIMARY KEY(team_id,user_id),INDEX idx_org_team_member_user(user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_business_groups (id varchar(64) PRIMARY KEY,name varchar(255) NOT NULL,note text,parent_id varchar(64),created_at datetime,updated_at datetime,INDEX idx_org_business_parent(parent_id),INDEX idx_org_business_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_business_group_teams (business_group_id varchar(64) NOT NULL,team_id varchar(64) NOT NULL,perm_flag varchar(8) DEFAULT 'rw',created_at datetime,PRIMARY KEY(business_group_id,team_id),INDEX idx_org_business_team(team_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_roles (id varchar(64) PRIMARY KEY,name varchar(128) UNIQUE NOT NULL,note text,builtin tinyint(1) DEFAULT 0,created_at datetime,updated_at datetime) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_user_roles (user_id varchar(64) NOT NULL,role_id varchar(64) NOT NULL,created_at datetime,PRIMARY KEY(user_id,role_id),INDEX idx_org_user_role_role(role_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS org_role_operations (role_id varchar(64) NOT NULL,operation varchar(128) NOT NULL,created_at datetime,PRIMARY KEY(role_id,operation)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	// GB-001: knowledge base tables
	`CREATE TABLE IF NOT EXISTS diagnosis_cases (id VARCHAR(64) PRIMARY KEY,metric_snapshot JSON NOT NULL,root_cause_category VARCHAR(64) NOT NULL,root_cause_description TEXT NOT NULL,treatment_steps TEXT NOT NULL,keywords VARCHAR(500),source_diagnosis_id VARCHAR(64),dify_document_id VARCHAR(64),created_at DATETIME NOT NULL,created_by VARCHAR(128),evaluation_avg DECIMAL(3,1) DEFAULT 0,INDEX idx_case_category(root_cause_category),FULLTEXT INDEX idx_case_keywords(keywords,root_cause_description)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS diagnosis_feedback (id VARCHAR(64) PRIMARY KEY,diagnosis_id VARCHAR(64) NOT NULL,user VARCHAR(128) NOT NULL,rating ENUM('accurate','partial','inaccurate') NOT NULL,comment TEXT,dify_message_id VARCHAR(64),created_at DATETIME NOT NULL,INDEX idx_feedback_diagnosis(diagnosis_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS ai_settings (id VARCHAR(64) PRIMARY KEY,setting_key VARCHAR(128) UNIQUE NOT NULL,setting_value TEXT,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS runbooks (id VARCHAR(64) PRIMARY KEY,title VARCHAR(255) NOT NULL,category VARCHAR(64) NOT NULL,trigger_conditions JSON,steps TEXT NOT NULL,auto_executable TINYINT(1) DEFAULT 0,dify_document_id VARCHAR(64),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_runbook_category(category)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS metrics_mappings (id VARCHAR(64) PRIMARY KEY,datasource_id VARCHAR(64) NOT NULL,raw_name VARCHAR(255) NOT NULL,standard_name VARCHAR(255),exporter VARCHAR(64),description VARCHAR(500),transform VARCHAR(500),status ENUM('auto','confirmed','custom','unmapped') DEFAULT 'unmapped',created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uniq_ds_raw(datasource_id,raw_name),INDEX idx_mapping_standard(standard_name),INDEX idx_mapping_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_targets (id VARCHAR(64) PRIMARY KEY,ident VARCHAR(255) UNIQUE NOT NULL,name VARCHAR(255),ip VARCHAR(64),hostname VARCHAR(255),os VARCHAR(64),arch VARCHAR(64),environment VARCHAR(64),business_group VARCHAR(128),owner VARCHAR(128),status VARCHAR(32),source VARCHAR(64),labels JSON,metadata JSON,last_seen DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_monitor_target_ip(ip),INDEX idx_monitor_target_status(status),INDEX idx_monitor_target_bg(business_group)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agents (id VARCHAR(64) PRIMARY KEY,ident VARCHAR(255) UNIQUE NOT NULL,target_id VARCHAR(64),ip VARCHAR(64),hostname VARCHAR(255),os VARCHAR(64),arch VARCHAR(64),version VARCHAR(128),collector VARCHAR(64),status VARCHAR(32),capabilities JSON,global_labels JSON,config_version VARCHAR(128),last_seen DATETIME NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_findx_agent_ip(ip),INDEX idx_findx_agent_status(status),INDEX idx_findx_agent_target(target_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_install_plans (id VARCHAR(64) PRIMARY KEY,package_id VARCHAR(128) NOT NULL,os VARCHAR(64),method VARCHAR(64),target_ids JSON,credential_ref_present TINYINT(1) DEFAULT 0,status VARCHAR(32),blocker TEXT,audit VARCHAR(128),evidence_refs JSON,metadata JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_faip_package(package_id),INDEX idx_faip_status(status),INDEX idx_faip_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_install_executions (id VARCHAR(64) PRIMARY KEY,plan_id VARCHAR(64) NOT NULL,target_id VARCHAR(64),runner VARCHAR(64),status VARCHAR(32),exit_code INT NULL,steps JSON,evidence_refs JSON,error_summary TEXT,created_at DATETIME NOT NULL,started_at DATETIME NULL,finished_at DATETIME NULL,updated_at DATETIME NOT NULL,INDEX idx_faie_plan(plan_id),INDEX idx_faie_target(target_id),INDEX idx_faie_status(status),INDEX idx_faie_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_config_rollouts (id VARCHAR(64) PRIMARY KEY,template_id VARCHAR(128) NOT NULL,agent_ids JSON,target_ids JSON,config_version VARCHAR(128),config_snippet_ref VARCHAR(255),config_format VARCHAR(32),provider_mode VARCHAR(64),plugin_id VARCHAR(255),plugin_version VARCHAR(128),reload_strategy VARCHAR(128),restart_strategy VARCHAR(128),rollout_strategy VARCHAR(128),rollback_ref VARCHAR(255),audit_reason TEXT,change_ticket VARCHAR(255),remote_mutation TINYINT(1) DEFAULT 0,canary_percent INT DEFAULT 0,credential_ref_present TINYINT(1) DEFAULT 0,status VARCHAR(32),blocker TEXT,audit VARCHAR(128),evidence_refs JSON,metadata JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_facr_template(template_id),INDEX idx_facr_status(status),INDEX idx_facr_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_plugin_assignments (id VARCHAR(64) PRIMARY KEY,source_rollout_id VARCHAR(64),host_ref VARCHAR(128) NOT NULL,agent_ref VARCHAR(128) NOT NULL,plugin_id VARCHAR(255) NOT NULL,plugin_version VARCHAR(128),config_snippet_ref VARCHAR(255),config_format VARCHAR(32),provider_mode VARCHAR(64),target_binding_ref VARCHAR(64),audit_ref VARCHAR(128),assignment_contract VARCHAR(128),status VARCHAR(32),blocker VARCHAR(255),credential_ref_present TINYINT(1) DEFAULT 0,dashboard_refs JSON,dashboard_refs_count INT DEFAULT 0,missing_contracts_json JSON,metadata_json JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_fapa_host_agent_plugin(host_ref,agent_ref,plugin_id),INDEX idx_fapa_rollout(source_rollout_id),INDEX idx_fapa_status(status),INDEX idx_fapa_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_plugin_target_bindings (id VARCHAR(64) PRIMARY KEY,assignment_id VARCHAR(64) NOT NULL,source_rollout_id VARCHAR(64),host_ref VARCHAR(128) NOT NULL,target_id VARCHAR(128),agent_ref VARCHAR(128) NOT NULL,plugin_id VARCHAR(255) NOT NULL,binding_type VARCHAR(64),status VARCHAR(32),blocker VARCHAR(255),credential_ref_present TINYINT(1) DEFAULT 0,dashboard_refs_count INT DEFAULT 0,contract_id VARCHAR(128),audit_ref VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_fapt_assignment(assignment_id),INDEX idx_fapt_host_agent_plugin(host_ref,agent_ref,plugin_id),INDEX idx_fapt_rollout(source_rollout_id),INDEX idx_fapt_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_execution_tasks (id VARCHAR(64) PRIMARY KEY,action VARCHAR(64) NOT NULL,agent_ids JSON,target_ids JSON,package_id VARCHAR(128),config_version VARCHAR(128),credential_ref_present TINYINT(1) DEFAULT 0,status VARCHAR(32),blocker TEXT,audit VARCHAR(128),evidence_refs JSON,metadata JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_faet_action(action),INDEX idx_faet_status(status),INDEX idx_faet_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS findx_agent_data_arrival_evidence (id VARCHAR(64) PRIMARY KEY,kind VARCHAR(64) NOT NULL,agent_id VARCHAR(64),target_id VARCHAR(64),status VARCHAR(32),blocker TEXT,evidence_refs JSON,metadata JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_fade_kind(kind),INDEX idx_fade_agent(agent_id),INDEX idx_fade_target(target_id),INDEX idx_fade_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_checks (id VARCHAR(64) PRIMARY KEY,name VARCHAR(160) NOT NULL,type VARCHAR(16),url TEXT,target VARCHAR(512),port INT DEFAULT 0,http_config JSON,dns_config JSON,interval_seconds INT DEFAULT 60,timeout_seconds INT DEFAULT 10,retries INT DEFAULT 0,status VARCHAR(32),enabled TINYINT(1) DEFAULT 0,business_group VARCHAR(160),labels JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_check_type(type),INDEX idx_probe_check_status(status),INDEX idx_probe_check_enabled(enabled),INDEX idx_probe_check_bg(business_group)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_check_results (id VARCHAR(64) PRIMARY KEY,check_id VARCHAR(64) NOT NULL,status VARCHAR(32),response_time_ms INT DEFAULT 0,status_code INT DEFAULT 0,error TEXT,region VARCHAR(80),evidence_ref VARCHAR(512),metadata JSON,checked_at DATETIME NOT NULL,created_at DATETIME NOT NULL,INDEX idx_probe_result_check_time(check_id,checked_at),INDEX idx_probe_result_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_status_pages (id VARCHAR(64) PRIMARY KEY,slug VARCHAR(120) UNIQUE NOT NULL,title VARCHAR(160) NOT NULL,description VARCHAR(512),business_group VARCHAR(160),visibility VARCHAR(32),status_groups JSON,labels JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_page_bg(business_group)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_incidents (id VARCHAR(64) PRIMARY KEY,check_id VARCHAR(64),status_page_id VARCHAR(64),title VARCHAR(180) NOT NULL,status VARCHAR(32),severity VARCHAR(32),message TEXT,business_group VARCHAR(160),labels JSON,started_at DATETIME NOT NULL,resolved_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_incident_check(check_id),INDEX idx_probe_incident_page(status_page_id),INDEX idx_probe_incident_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_subscriptions (id VARCHAR(64) PRIMARY KEY,status_page_id VARCHAR(64) NOT NULL,receiver VARCHAR(180),channel_type VARCHAR(32),enabled TINYINT(1) DEFAULT 0,verified_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_subscription_page(status_page_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_notification_bindings (id VARCHAR(64) PRIMARY KEY,check_id VARCHAR(64),status_page_id VARCHAR(64),channel_id VARCHAR(64),enabled TINYINT(1) DEFAULT 0,receipt_mode VARCHAR(64),last_receipt_ref VARCHAR(512),labels JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_notify_check(check_id),INDEX idx_probe_notify_page(status_page_id),INDEX idx_probe_notify_channel(channel_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS probe_alert_bindings (id VARCHAR(64) PRIMARY KEY,check_id VARCHAR(64),alert_rule_id VARCHAR(64),enabled TINYINT(1) DEFAULT 0,last_evidence_ref VARCHAR(512),labels JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_probe_alert_check(check_id),INDEX idx_probe_alert_rule(alert_rule_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_dashboards (id VARCHAR(64) PRIMARY KEY,title VARCHAR(255) NOT NULL,description TEXT,workspace_id VARCHAR(64),resource_group_id VARCHAR(64),tags JSON,variables JSON,panels JSON,version INT NOT NULL DEFAULT 1,status VARCHAR(32),shared TINYINT(1) DEFAULT 0,share_token_hash VARCHAR(128),created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_md_workspace(workspace_id),INDEX idx_md_resource_group(resource_group_id),INDEX idx_md_status(status),INDEX idx_md_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_builtin_components (id VARCHAR(64) PRIMARY KEY,ident VARCHAR(128) UNIQUE NOT NULL,name VARCHAR(255) NOT NULL,logo TEXT,readme LONGTEXT,disabled TINYINT(1) DEFAULT 0,updated_by VARCHAR(128),updated_at DATETIME NOT NULL,INDEX idx_mbc_ident(ident)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_builtin_payloads (id VARCHAR(64) PRIMARY KEY,uuid VARCHAR(64) UNIQUE NOT NULL,type VARCHAR(32) NOT NULL,component_id VARCHAR(64) NOT NULL,cate VARCHAR(128),name VARCHAR(255) NOT NULL,content LONGTEXT NOT NULL,updated_by VARCHAR(128),updated_at DATETIME NOT NULL,INDEX idx_mbp_component_type(component_id,type),INDEX idx_mbp_uuid(uuid)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_system_integrations (id VARCHAR(64) PRIMARY KEY,weight INT NOT NULL DEFAULT 0,name VARCHAR(120) NOT NULL,url TEXT NOT NULL,config_preview TEXT NOT NULL,is_private TINYINT(1) DEFAULT 0,team_ids JSON,hide TINYINT(1) DEFAULT 0,status VARCHAR(32) NOT NULL,builtin TINYINT(1) DEFAULT 0,created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_msi_weight(weight),INDEX idx_msi_status(status),INDEX idx_msi_builtin(builtin)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS resource_groups (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT,workspace_id VARCHAR(64),parent_id VARCHAR(64),status VARCHAR(32),tags JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_rg_workspace_status(workspace_id,status),INDEX idx_rg_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_rules (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,query LONGTEXT NOT NULL,severity VARCHAR(32) NOT NULL,datasource_id VARCHAR(64) NOT NULL,target_selector JSON,labels JSON,annotations JSON,enabled TINYINT(1) DEFAULT 1,version INT NOT NULL DEFAULT 1,for_duration VARCHAR(64),no_data_policy VARCHAR(32),status VARCHAR(32),created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_mar_ds(datasource_id),INDEX idx_mar_status(status),INDEX idx_mar_enabled(enabled)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_rule_versions (id VARCHAR(96) PRIMARY KEY,rule_id VARCHAR(64) NOT NULL,version INT NOT NULL,name VARCHAR(255) NOT NULL,query LONGTEXT NOT NULL,severity VARCHAR(32) NOT NULL,datasource_id VARCHAR(64) NOT NULL,target_selector JSON,labels JSON,annotations JSON,enabled TINYINT(1) DEFAULT 1,for_duration VARCHAR(64),no_data_policy VARCHAR(32),status VARCHAR(32),created_by VARCHAR(128),created_at DATETIME NOT NULL,UNIQUE KEY uniq_marv_rule_version(rule_id,version),INDEX idx_marv_rule(rule_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_rule_eval_logs (id VARCHAR(64) PRIMARY KEY,rule_id VARCHAR(64),rule_version INT,status VARCHAR(32),message TEXT,details JSON,started_at DATETIME NOT NULL,finished_at DATETIME NOT NULL,duration_ms BIGINT DEFAULT 0,datasource_id VARCHAR(64),query_hash VARCHAR(64),INDEX idx_marel_rule(rule_id,started_at),INDEX idx_marel_status(status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_events_current (id VARCHAR(64) PRIMARY KEY,rule_id VARCHAR(64),rule_version INT,event_key VARCHAR(255),name VARCHAR(255),severity VARCHAR(32),status VARCHAR(32),datasource_id VARCHAR(64),target_id VARCHAR(64),target_ident VARCHAR(255),labels JSON,annotations JSON,value VARCHAR(255),fingerprint VARCHAR(128),count INT DEFAULT 1,first_seen DATETIME NOT NULL,last_seen DATETIME NOT NULL,ack_by VARCHAR(128),assignee VARCHAR(128),resolution TEXT,archived_at DATETIME NULL,resolved_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uniq_maec_fp(fingerprint),INDEX idx_maec_status(status),INDEX idx_maec_rule(rule_id),INDEX idx_maec_last(last_seen)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_events_history (id VARCHAR(64) PRIMARY KEY,rule_id VARCHAR(64),rule_version INT,event_key VARCHAR(255),name VARCHAR(255),severity VARCHAR(32),status VARCHAR(32),datasource_id VARCHAR(64),target_id VARCHAR(64),target_ident VARCHAR(255),labels JSON,annotations JSON,value VARCHAR(255),fingerprint VARCHAR(128),count INT DEFAULT 1,first_seen DATETIME NOT NULL,last_seen DATETIME NOT NULL,ack_by VARCHAR(128),assignee VARCHAR(128),resolution TEXT,archived_at DATETIME NULL,resolved_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_maeh_status(status),INDEX idx_maeh_rule(rule_id),INDEX idx_maeh_last(last_seen)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS monitor_alert_event_actions (id VARCHAR(64) PRIMARY KEY,event_id VARCHAR(64) NOT NULL,action VARCHAR(32) NOT NULL,actor VARCHAR(128),` + "`from`" + ` VARCHAR(32),` + "`to`" + ` VARCHAR(32),reason TEXT,assignee VARCHAR(128),trace_id VARCHAR(128),created_at DATETIME NOT NULL,INDEX idx_maea_event(event_id),INDEX idx_maea_time(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS log_pipelines (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,version_id VARCHAR(128) NOT NULL,description TEXT,enabled TINYINT(1) DEFAULT 0,stages JSON,config JSON,created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_log_pipeline_version(version_id),INDEX idx_log_pipeline_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS explorer_saved_views (id VARCHAR(64) PRIMARY KEY,source_page VARCHAR(64) NOT NULL,name VARCHAR(255) NOT NULL,description TEXT,query_json JSON,filters JSON,columns_json JSON,time_range JSON,layout JSON,created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_explorer_view_source(source_page),INDEX idx_explorer_view_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS workflows (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT,dsl LONGTEXT,builtin TINYINT(1) DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_wf_name(name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS workflow_versions (id VARCHAR(96) PRIMARY KEY,workflow_id VARCHAR(64) NOT NULL,version INT NOT NULL,name VARCHAR(255) NOT NULL,description TEXT,dsl LONGTEXT,created_at DATETIME NOT NULL,UNIQUE KEY uniq_wfv_workflow_version(workflow_id,version),INDEX idx_wfv_workflow(workflow_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS workflow_runs (id VARCHAR(64) PRIMARY KEY,workflow_id VARCHAR(64) NOT NULL,status VARCHAR(32) NOT NULL,inputs LONGTEXT,outputs LONGTEXT,error_message TEXT,elapsed_ms BIGINT DEFAULT 0,created_at DATETIME NOT NULL,INDEX idx_wfr_wf(workflow_id),INDEX idx_wfr_time(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	// 知识库文档与搜索事件表。
	`CREATE TABLE IF NOT EXISTS knowledge_documents (id VARCHAR(64) PRIMARY KEY,title VARCHAR(500) NOT NULL,content LONGTEXT NOT NULL,doc_type VARCHAR(32) NOT NULL,file_type VARCHAR(32),file_name VARCHAR(500),file_size INT DEFAULT 0,category VARCHAR(64),tags VARCHAR(500),source_id VARCHAR(64),embedding_model VARCHAR(100),chunk_index INT DEFAULT 0,parent_id VARCHAR(64),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FULLTEXT INDEX idx_doc_content(title,content),INDEX idx_doc_type(doc_type),INDEX idx_doc_category(category),INDEX idx_doc_parent(parent_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS knowledge_search_events (id VARCHAR(64) PRIMARY KEY,query VARCHAR(500) NOT NULL,hit_count INT DEFAULT 0,top_score DOUBLE DEFAULT 0,engine VARCHAR(32),created_at DATETIME NOT NULL,INDEX idx_kse_created(created_at),INDEX idx_kse_query(query)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS knowledge_search_badcases (id VARCHAR(64) PRIMARY KEY,query VARCHAR(500) NOT NULL,doc_id VARCHAR(64) NOT NULL,reason TEXT,created_by VARCHAR(128),created_at DATETIME NOT NULL,INDEX idx_ksb_created(created_at),INDEX idx_ksb_query(query)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS notification_channels (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,type VARCHAR(32) NOT NULL,webhook TEXT,endpoint TEXT,enabled TINYINT(1) DEFAULT 1,config JSON,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_nc_type(type),INDEX idx_nc_enabled(enabled)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS notification_rules (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT,enabled TINYINT(1) DEFAULT 1,user_group_ids JSON,notify_configs JSON NOT NULL,alert_rule_ids JSON,event_pipeline_configs JSON,conditions JSON,time_window JSON,extra JSON,created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_nr_enabled(enabled)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS notification_templates (id VARCHAR(64) PRIMARY KEY,name VARCHAR(255) NOT NULL,channel_type VARCHAR(32),content LONGTEXT,variables JSON,created_by VARCHAR(128),updated_by VARCHAR(128),created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
}

var tolerantMigrationStatements = []string{
	`ALTER TABLE alerts ADD COLUMN annotations json`,
	`ALTER TABLE alerts ADD COLUMN business_id varchar(64)`,
	`ALTER TABLE alerts ADD COLUMN fingerprint varchar(128)`,
	`ALTER TABLE alerts ADD COLUMN count int DEFAULT 1`,
	`ALTER TABLE alerts ADD COLUMN first_seen datetime`,
	`ALTER TABLE alerts ADD COLUMN last_seen datetime`,
	`ALTER TABLE alerts ADD COLUMN ack_by varchar(128)`,
	`ALTER TABLE alerts ADD COLUMN assignee varchar(128)`,
	`ALTER TABLE alerts ADD COLUMN muted_until datetime NULL`,
	`ALTER TABLE alerts ADD COLUMN deleted_at datetime NULL`,
	`ALTER TABLE alerts ADD COLUMN test_batch_id varchar(128)`,
	`ALTER TABLE alerts ADD COLUMN audit_trace_id varchar(128)`,
	`ALTER TABLE alerts ADD COLUMN diagnose_record_id varchar(64)`,
	`ALTER TABLE alerts ADD COLUMN linked_business_id varchar(64)`,
	`ALTER TABLE alerts ADD COLUMN resolution text`,
	`ALTER TABLE alerts ADD COLUMN runbook_url text`,
	`ALTER TABLE alerts ADD COLUMN action_log json`,
	`ALTER TABLE alerts ADD COLUMN notification_trail json`,
	`ALTER TABLE alerts ADD INDEX idx_alert_fingerprint(fingerprint)`,
	`ALTER TABLE alerts ADD INDEX idx_alert_status(status)`,
	`ALTER TABLE topology_edges ADD COLUMN status varchar(32)`,
	`ALTER TABLE topology_edges ADD COLUMN latency_ms int`,
	`ALTER TABLE topology_edges ADD COLUMN error text`,
	`ALTER TABLE topology_businesses ADD COLUMN attributes json`,
	// Runbook 执行统计和回滚字段。
	`ALTER TABLE runbooks ADD COLUMN version INT DEFAULT 1`,
	`ALTER TABLE runbooks ADD COLUMN severity VARCHAR(32) DEFAULT 'medium'`,
	`ALTER TABLE runbooks ADD COLUMN estimated_time VARCHAR(32) DEFAULT ''`,
	`ALTER TABLE runbooks ADD COLUMN prerequisites TEXT`,
	`ALTER TABLE runbooks ADD COLUMN rollback_steps TEXT`,
	`ALTER TABLE runbooks ADD COLUMN variables JSON`,
	`ALTER TABLE runbooks ADD COLUMN last_executed_at DATETIME`,
	`ALTER TABLE runbooks ADD COLUMN execution_count INT DEFAULT 0`,
	`ALTER TABLE runbooks ADD COLUMN success_rate DECIMAL(5,2) DEFAULT 0`,
	`ALTER TABLE audit_events ADD COLUMN integrity_hash VARCHAR(128) DEFAULT ''`,
	`ALTER TABLE audit_events ADD COLUMN operator VARCHAR(128) DEFAULT ''`,
	`ALTER TABLE audit_events ADD COLUMN description TEXT`,
	// v6: change events table
	`CREATE TABLE IF NOT EXISTS change_events (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			target_ip VARCHAR(64) NOT NULL,
			change_type VARCHAR(32) NOT NULL,
			title VARCHAR(512) NOT NULL,
			description TEXT,
			operator VARCHAR(128),
			source VARCHAR(64),
			started_at DATETIME NOT NULL,
			completed_at DATETIME,
			status VARCHAR(16) DEFAULT 'completed',
			metadata JSON,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			INDEX idx_change_ip_time (target_ip, started_at)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	`CREATE TABLE IF NOT EXISTS workflow_schedules (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			workflow_name VARCHAR(128) NOT NULL,
			cron_expr VARCHAR(64) NOT NULL,
			inputs_json JSON,
			enabled BOOLEAN DEFAULT TRUE,
			last_run DATETIME,
			next_run DATETIME,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	// v6: prompt templates table
	`CREATE TABLE IF NOT EXISTS prompt_templates (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			name VARCHAR(128) NOT NULL UNIQUE,
			category VARCHAR(64),
			template TEXT NOT NULL,
			version INT NOT NULL DEFAULT 1,
			variables JSON,
			description TEXT,
			is_active BOOLEAN DEFAULT TRUE,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	// v6: diagnosis verifications table
	`CREATE TABLE IF NOT EXISTS diagnosis_verifications (
			id BIGINT AUTO_INCREMENT PRIMARY KEY,
			diagnosis_id VARCHAR(64) NOT NULL,
			alert_resolution_rate FLOAT,
			recurrence_count INT DEFAULT 0,
			runbook_executed BOOLEAN DEFAULT FALSE,
			runbook_success BOOLEAN DEFAULT FALSE,
			score FLOAT,
			verified_at DATETIME,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
			INDEX idx_dv_diagnosis (diagnosis_id)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
	// v6: diagnosis case extension fields
	`ALTER TABLE diagnosis_cases ADD COLUMN diagnostic_path JSON`,
	`ALTER TABLE diagnosis_cases ADD COLUMN distinguishing_features TEXT`,
	`ALTER TABLE diagnosis_cases ADD COLUMN negative_findings JSON`,
	`ALTER TABLE diagnosis_cases ADD COLUMN avg_feedback_rating FLOAT DEFAULT 0`,
	`ALTER TABLE diagnosis_cases ADD COLUMN verification_status VARCHAR(16) DEFAULT 'auto'`,
	// v6: workflow version extension fields
	`ALTER TABLE workflows ADD COLUMN version INT DEFAULT 1`,
	`ALTER TABLE workflow_runs ADD COLUMN workflow_version INT DEFAULT 1`,
	`ALTER TABLE workflow_runs ADD COLUMN parent_run_id VARCHAR(64)`,
	`INSERT IGNORE INTO workflow_versions (id,workflow_id,version,name,description,dsl,created_at) SELECT CONCAT(id, ':v', COALESCE(version,1)),id,COALESCE(version,1),name,COALESCE(description,''),dsl,COALESCE(updated_at,created_at,NOW()) FROM workflows`,
}
