package main

import (
	"ai-workbench-api/internal/handler"

	"github.com/gin-gonic/gin"
)

func registerAIOpsRoutes(v1 *gin.RouterGroup, mw routeMiddleware) {
	v1.GET("/models", handler.Models)
	v1.POST("/chat", handler.Chat)
	v1.GET("/chat/sessions", handler.ListChatSessions)
	v1.POST("/chat/sessions", handler.CreateChatSession)
	v1.GET("/chat/sessions/:id", handler.GetChatSession)
	v1.PUT("/chat/sessions/:id", handler.RenameChatSession)
	v1.DELETE("/chat/sessions/:id", handler.DeleteChatSession)
	v1.POST("/agent/llm/chat", handler.AgentLLMChat)
	v1.POST("/aiops/sessions", handler.AIOpsCreateSession)
	v1.POST("/aiops/sessions/:id/messages", handler.AIOpsPostMessage)
	v1.GET("/aiops/sessions/:id/messages", handler.AIOpsGetMessages)
	v1.GET("/aiops/ws/sessions/:id", handler.AIOpsSessionWS)
	v1.POST("/aiops/sessions/:id/actions/execute", mw.adminRequired, handler.AIOpsExecuteAction)
	v1.POST("/aiops/inspections", mw.adminRequired, handler.AIOpsCreateInspection)
	v1.GET("/aiops/inspections/:id/progress", handler.AIOpsInspectionProgress)
	v1.GET("/aiops/inspections/:id/report", handler.AIOpsInspectionReport)
	v1.GET("/aiops/evidence-chain", mw.readRequired, handler.AIOpsEvidenceChain)
	v1.POST("/aiops/data/prometheus/query", mw.adminRequired, handler.AIOpsPrometheusQuery)
	v1.POST("/aiops/data/prometheus/query_range", mw.adminRequired, handler.AIOpsPrometheusQueryRange)
	v1.POST("/aiops/data/catpaw/query", mw.adminRequired, handler.AIOpsCatpawQuery)
	v1.POST("/aiops/topology/generate", mw.adminRequired, handler.AIOpsTopologyGenerate)
}

func registerDiagnoseAndAgentRoutes(v1 *gin.RouterGroup, mw routeMiddleware) {
	v1.POST("/diagnose", mw.adminRequired, handler.StartDiagnose)
	v1.GET("/diagnose", handler.ListDiagnose)
	v1.GET("/diagnose/compare", handler.CompareDiagnoses)
	v1.DELETE("/diagnose", mw.adminRequired, handler.CleanupDiagnose)
	v1.DELETE("/diagnose/:id", mw.adminRequired, handler.DeleteDiagnose)
	v1.POST("/catpaw/heartbeat", handler.CatpawHeartbeat)
	v1.POST("/catpaw/report", handler.CatpawReport)
	v1.GET("/catpaw/agents", handler.ListAgents)
	v1.DELETE("/catpaw/agents/:ip", mw.adminRequired, handler.DeleteAgent)
	v1.POST("/alert/webhook", handler.AlertWebhook)
	v1.POST("/alert/catpaw", handler.CatpawAlert)
	v1.GET("/alerts", handler.ListAlerts)
	v1.PUT("/alerts/:id/resolve", mw.adminRequired, handler.ResolveAlert)
	v1.PUT("/alerts/:id/:action", mw.adminRequired, handler.AlertAction)
	v1.DELETE("/alerts/:id", mw.adminRequired, handler.DeleteAlert)
	v1.POST("/remote/exec", mw.adminRequired, handler.RemoteExec)
	v1.POST("/remote/check-port", mw.adminRequired, handler.CheckRemotePort)
	v1.POST("/remote/install-catpaw", mw.adminRequired, handler.InstallCatpaw)
	v1.POST("/remote/uninstall-catpaw", mw.adminRequired, handler.UninstallCatpaw)
	v1.POST("/remote/install-cmd", mw.adminRequired, handler.GenerateInstallCmd)
	v1.GET("/catpaw/chat-ws", handler.CatpawChat)
}

func registerPlatformRoutes(v1 *gin.RouterGroup, mw routeMiddleware) {
	v1.GET("/platform/ip", handler.GetPlatformIP)
	v1.GET("/prometheus/instances", handler.GetPrometheusInstances)
	v1.GET("/prometheus/hosts", handler.PrometheusHosts)
	v1.GET("/prometheus/metrics", handler.PrometheusMetrics)
	v1.GET("/health/datasources", handler.CheckDataSourceHealth)
	v1.GET("/health/ai-providers", handler.CheckAIProviderHealth)
	v1.GET("/health/storage", handler.HealthStorage)
	v1.GET("/audit/events", mw.readRequired, handler.ListAuditEvents)
	v1.GET("/oncall/config", handler.GetOnCallConfig)
	v1.POST("/oncall/config", mw.adminRequired, handler.SaveOnCallConfig)
	v1.GET("/oncall/groups", handler.ListOnCallGroups)
	v1.POST("/oncall/groups", mw.adminRequired, handler.SaveOnCallGroup)
	v1.DELETE("/oncall/groups/:id", mw.adminRequired, handler.DeleteOnCallGroup)
	v1.GET("/oncall/channels", handler.ListOnCallChannels)
	v1.POST("/oncall/channels", mw.adminRequired, handler.SaveOnCallChannel)
	v1.DELETE("/oncall/channels/:id", mw.adminRequired, handler.DeleteOnCallChannel)
	v1.GET("/oncall/schedules", handler.ListOnCallSchedules)
	v1.POST("/oncall/schedules", mw.adminRequired, handler.SaveOnCallSchedule)
	v1.DELETE("/oncall/schedules/:id", mw.adminRequired, handler.DeleteOnCallSchedule)
	v1.GET("/oncall/records", handler.ListOnCallRecords)
	v1.POST("/oncall/test-send", mw.adminRequired, handler.TestOnCallNotification)
}

func registerAssetsAndLogsRoutes(v1 *gin.RouterGroup, mw routeMiddleware) {
	v1.GET("/topology", handler.GetTopology)
	v1.POST("/topology", mw.adminRequired, handler.SaveTopology)
	v1.GET("/topology/resources", handler.TopologyResources)
	v1.POST("/topology/discover", mw.adminRequired, handler.DiscoverTopology)
	v1.POST("/topology/ai/generate", mw.adminRequired, handler.GenerateAITopology)
	v1.GET("/topology/businesses", handler.ListTopologyBusinesses)
	v1.POST("/topology/businesses", mw.adminRequired, handler.SaveTopologyBusiness)
	v1.GET("/topology/businesses/:id", handler.GetTopologyBusiness)
	v1.GET("/topology/businesses/:id/inspect", handler.InspectTopologyBusiness)
	v1.DELETE("/topology/businesses/:id", mw.adminRequired, handler.DeleteTopologyBusiness)
	v1.GET("/workspaces", mw.readRequired, handler.ListWorkspaces)
	v1.POST("/workspaces", mw.roleAdminRequired, handler.CreateWorkspace)
	v1.GET("/workspaces/:id", mw.readRequired, handler.GetWorkspace)
	v1.PUT("/workspaces/:id", mw.roleAdminRequired, handler.UpdateWorkspace)
	v1.DELETE("/workspaces/:id", mw.roleAdminRequired, handler.DeleteWorkspace)
	v1.GET("/resource-groups", mw.readRequired, handler.ListResourceGroups)
	v1.POST("/resource-groups", mw.roleAdminRequired, handler.CreateResourceGroup)
	v1.GET("/resource-groups/:id", mw.readRequired, handler.GetResourceGroup)
	v1.PUT("/resource-groups/:id", mw.roleAdminRequired, handler.UpdateResourceGroup)
	v1.DELETE("/resource-groups/:id", mw.roleAdminRequired, handler.DeleteResourceGroup)
	v1.GET("/host-assets", mw.readRequired, handler.ListHostAssets)
	v1.GET("/host-assets/:id", mw.readRequired, handler.GetHostAsset)
	v1.PUT("/host-assets/:id/tags", mw.roleAdminRequired, handler.UpdateHostAssetTags)
	v1.PUT("/host-assets/:id/resource-group", mw.roleAdminRequired, handler.UpdateHostAssetResourceGroup)
	v1.PUT("/host-assets/:id/workspace", mw.roleAdminRequired, handler.UpdateHostAssetWorkspace)
	registerLogRoutes(v1, mw)
}

func registerLogRoutes(v1 *gin.RouterGroup, mw routeMiddleware) {
	v1.GET("/ai-providers", handler.GetAIProviders)
	v1.POST("/ai-providers", mw.adminRequired, handler.SaveAIProviders)
	v1.GET("/data-sources", handler.GetDataSources)
	v1.POST("/data-sources", mw.adminRequired, handler.SaveDataSources)
	v1.GET("/logs/fields", mw.readRequired, handler.ListLogFields)
	v1.GET("/logs/pipelines/:version", mw.readRequired, handler.ListLogPipelines)
	v1.POST("/logs/pipelines", mw.adminRequired, handler.SaveLogPipeline)
	v1.PUT("/logs/pipelines/:id", mw.adminRequired, handler.UpdateLogPipelineBlocked)
	v1.DELETE("/logs/pipelines/:id", mw.adminRequired, handler.DeleteLogPipelineBlocked)
	v1.POST("/logs/pipelines/preview", mw.readRequired, handler.PreviewLogPipeline)
	v1.POST("/logs/pipelines/:id/deploy", mw.adminRequired, handler.DeployLogPipelineBlocked)
	v1.POST("/logs/pipelines/:id/rollback", mw.adminRequired, handler.RollbackLogPipelineBlocked)
	v1.GET("/logs", mw.readRequired, handler.ListLogsBlocked)
	v1.POST("/logs/query", mw.readRequired, handler.LogsQueryProxy)
	v1.GET("/logs/labels", mw.readRequired, handler.LogsLabelsProxy)
	v1.GET("/logs/label-values", mw.readRequired, handler.LogsLabelValuesProxy)
	v1.GET("/logs/tail", mw.readRequired, handler.LogsTailSSEProxy)
	v1.GET("/logs/aggregate", mw.readRequired, handler.AggregateLogsBlocked)
	v1.GET("/logs/context", mw.readRequired, handler.GetLogContext)
	v1.GET("/logs/realtime", mw.readRequired, handler.RealtimeLogsBlocked)
	v1.GET("/logs/stream", mw.readRequired, handler.RealtimeLogsBlocked)
	v1.GET("/explorer/views", mw.readRequired, handler.ListExplorerViews)
	v1.POST("/explorer/views", mw.adminRequired, handler.CreateExplorerView)
	v1.GET("/explorer/views/:id", mw.readRequired, handler.GetExplorerView)
	v1.PUT("/explorer/views/:id", mw.adminRequired, handler.UpdateExplorerView)
	v1.DELETE("/explorer/views", mw.adminRequired, handler.DeleteExplorerView)
	v1.DELETE("/explorer/views/:id", mw.adminRequired, handler.DeleteExplorerView)
}
